[ambient_emittance]
type = "Lorentzian"
maximum_at = 475e-9
fwhm = 15e-9
maximum = 10e9

[camera]
    location = [-1, 2, -6]
    look_at = [-0.5, 0.5, -1]
    vfov = 45
    up = [0, 1, 0]

# Sun
[[surfaces]]
    type = "Sphere"
    center = [13, 9.5, 20.0]
    radius = 5

    [surfaces.material]
        [surfaces.material.emittance]
            type = "BlackBody"
            temperature = 5557

# Earth:
[[surfaces]]
    type = "Sphere"
    center = [0.0, -21.0, 0.0]
    radius = 20.0

    [surfaces.material]
        [surfaces.material.reflectance]
            attenuation = { type = "Constant" }
            diffusion = 0.8
            fuzz = 0.02

# Central smaller sphere:
[[surfaces]]
    type = "Sphere"
    center = [0.0, 0.2, 0.0]
    radius = 1.0

    [surfaces.material]

        [surfaces.material.reflectance]
        attenuation = { type = "Lorentzian", maximum_at = 570e-9, fwhm = 100e-9 }
        diffusion = 0.01

# Small sphere on the left:
[[surfaces]]
    type = "Sphere"
    center = [-2.5, 0.0, 0.0]
    radius = 1.0

    [surfaces.material]

        [surfaces.material.reflectance]
        attenuation = { type = "Lorentzian", maximum_at = 520e-9, fwhm = 100e-9 }
        diffusion = 0.8

# Small sphere on the right:
[[surfaces]]
    type = "Sphere"
    center = [0.75, -0.5, -1.5]
    radius = 0.5

    [surfaces.material]

        [surfaces.material.reflectance.attenuation]
            type = "Constant"

        [surfaces.material.transmittance]
            refracted_index = { type = "Water" }
            attenuation = { type = "Water", scale = 0.05 } # FIXME: suspicious scale for a 1-meter ball.

# Another small sphere on the right:
[[surfaces]]
    type = "Sphere"
    center = [2, -0.5, 0.0]
    radius = 0.5

    [surfaces.material]
        [surfaces.material.reflectance.attenuation]
            type = "Constant"

        [surfaces.material.transmittance]
            refracted_index = { type = "FusedQuartz" }

            [surfaces.material.transmittance.attenuation]
                type = "Constant"
                coefficient = 0.5
