[ambient_emittance]
type = "Lorentzian"
maximum = 475e-9
fwhm = 15e-9
radiance = 0.1

[camera]
    location = [-1, 2, -6]
    look_at = [-0.5, 0.5, -1]
    vfov = 45
    up = [0, 1, 0]

# Sun
[[surfaces]]
    type = "Sphere"
    center = [13, 9.5, 20.0]
    radius = 5

    [surfaces.material]
        [surfaces.material.emittance]
            type = "BlackBody"
            temperature = 5557
            scale = 10e-12

# Earth:
[[surfaces]]
    type = "Sphere"
    center = [0.0, -21.0, 0.0]
    radius = 20.0

    [surfaces.material]
        [surfaces.material.reflectance]
            attenuation = { type = "Constant", intensity = 1 }
            diffusion = 0.99
            fuzz = 0.02

# Central smaller sphere:
[[surfaces]]
    type = "Sphere"
    center = [0.0, 0.2, 0.0]
    radius = 1.0

    [surfaces.material]

        [surfaces.material.reflectance]
        attenuation = { type = "Lorentzian", maximum = 570e-9, fwhm = 100e-9 }
        diffusion = 0.01

# Small sphere on the left:
[[surfaces]]
    type = "Sphere"
    center = [-2.5, 0.0, 0.0]
    radius = 1.0

    [surfaces.material]

        [surfaces.material.reflectance]
        attenuation = { type = "Lorentzian", maximum = 520e-9, fwhm = 100e-9 }
        diffusion = 0.8

# Small sphere on the right:
[[surfaces]]
    type = "Sphere"
    center = [0.75, -0.5, -1.5]
    radius = 0.5

    [surfaces.material]

        [surfaces.material.reflectance.attenuation]
            type = "Constant"

        [surfaces.material.transmittance]
            refracted_index = { type = "Water" }
            coefficient = { type = "Water", scale = 0.05 }

# Another small sphere on the right:
[[surfaces]]
    type = "Sphere"
    center = [2, -0.5, 0.0]
    radius = 0.5

    [surfaces.material]
        [surfaces.material.reflectance.attenuation]
            type = "Constant"

        [surfaces.material.transmittance]
            # Fused silica
            refracted_index = { type = "FusedQuartz" }

            [surfaces.material.transmittance.attenuation]
                type = "Sum"

                [[surfaces.material.transmittance.attenuation.spectra]]
                    type = "Constant"
                    intensity = 0.5

                [[surfaces.material.transmittance.attenuation.spectra]]
                    type = "Lorentzian"
                    maximum = 480e-9
                    fwhm = 50e-9
                    intensity = 0.5
