[ambient_spectrum]
type = "Constant"
intensity = 1
# temperature = 5557
# scale = 1e-14

[camera]
    location = [0, 4, -5]
    look_at = [0, 0, -1]
    vfov = 45
    up = [0, 1, 0]

# Big sphere underneath:

[[surfaces]]
    type = "Sphere"
    center = [0.0, -21.0, 0.0]
    radius = 20.0

    [surfaces.material]
        [surfaces.material.reflectance]
            attenuation = { type = "Constant", intensity = 0.95 }
            fuzz = 0.02

# Central smaller sphere:

[[surfaces]]
    type = "Sphere"
    center = [0.0, 0.2, 0.0]
    radius = 1.0

    [surfaces.material]

        [surfaces.material.reflectance]
        attenuation = { type = "Lorentzian", maximum = 570e-9, fwhm = 50e-9 }

# Small sphere on the left:

[[surfaces]]
    type = "Sphere"
    center = [-2.5, 0.0, 0.0]
    radius = 1.0

    [surfaces.material]

        [surfaces.material.reflectance]
        attenuation = { type = "Lorentzian", maximum = 520e-9, fwhm = 50e-9 }
        diffusion = 0.8

# Small sphere on the right:

[[surfaces]]
    type = "Sphere"
    center = [0.75, -0.5, -1.5]
    radius = 0.5

    [surfaces.material]

        [surfaces.material.reflectance.attenuation]
            type = "Constant"

        [surfaces.material.transmittance]
            refractive_index = 1.54
            coefficient = 0.1

            [surfaces.material.transmittance.attenuation]
                type = "Sum"

                [[surfaces.material.transmittance.attenuation.spectra]]
                    type = "Lorentzian"
                    maximum = 640e-9
                    fwhm = 50e-9
                    intensity = 0.5

                [[surfaces.material.transmittance.attenuation.spectra]]
                    type = "Constant"
                    intensity = 0.5

# Another small sphere on the right:

[[surfaces]]
    type = "Sphere"
    center = [2, -0.5, 0.0]
    radius = 0.5

    [surfaces.material]
        [surfaces.material.reflectance.attenuation]
            type = "Constant"

        [surfaces.material.transmittance]
            refractive_index = 1.54
            coefficient = 0

            [surfaces.material.transmittance.attenuation]
                type = "Sum"

                [[surfaces.material.transmittance.attenuation.spectra]]
                    type = "Constant"
                    intensity = 0.5

                [[surfaces.material.transmittance.attenuation.spectra]]
                    type = "Lorentzian"
                    maximum = 480e-9
                    fwhm = 50e-9
                    intensity = 0.5
