samples_per_pixel = 10

[viewport]
width = 1
distance = 5
focal_length = 1

[[surfaces]]
type = "Sphere"
center = [0.0, 0.0, 2.0]
radius = 1.0

[[surfaces]]
type = "Sphere"
center = [0.0, 0.0, 1.0]
radius = 0.5
