ambient_color = [1, 1, 1]

[viewport]
width = 1
distance = 10
focal_length = 1

# Big sphere underneath:

[[surfaces]]
type = "Sphere"
center = [0.0, -101.0, 0.0]
radius = 100.0

[surfaces.material]
albedo = 0.95
reflective_fuzz = 0.01

# Central small sphere:

[[surfaces]]
type = "Sphere"
center = [0.0, 0.1, 0.0]
radius = 1.0

[surfaces.material]
attenuation = [1, 1, 0.8]
albedo = 0.9

# Small sphere on the left:

[[surfaces]]
type = "Sphere"
center = [-2.5, 0.0, 0.0]
radius = 1.0

[surfaces.material]
attenuation = [0.8, 1, 0.8]
diffusion_probability = 0.75

# Small sphere on the right:

[[surfaces]]
type = "Sphere"
center = [0.75, -0.5, -1.5]
radius = 0.5

[surfaces.material]
attenuation = [1.0, 0.8, 0.8]
refractive_index = 1.54

# Another small sphere on the right:

[[surfaces]]
type = "Sphere"
center = [1.5, -0.5, 0.0]
radius = 0.5

[surfaces.material]
attenuation = [0.8, 0.8, 1.0]
refractive_index = 1.54
